<a href="https://colab.research.google.com/github/Abhishek-jakhar/Machine_learning/blob/main/Multiple_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

(100,)

In [6]:
x,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [13]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [8]:
df

feature1  feature2      target
0  -0.583626  0.045244  -93.282836
1   0.829983  1.060484  158.588990
2   0.495171  0.465414   74.488553
3   0.963453  1.843128  -51.719939
4  -0.635715 -1.566468   64.807919
..       ...       ...         ...
95  1.706626  1.085154  -29.676237
96  1.288527 -0.024162  -80.319566
97 -0.514527 -0.254291   22.793129
98  0.045228  0.997946  150.038598
99 -0.817480  0.111957  -37.485407

[100 rows x 3 columns]

In [14]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [21]:
px.scatter_3d(df,x='feature1',y='feature2',z='target')

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=3)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lr = LinearRegression()

In [30]:
lr.fit(x_train,y_train)

LinearRegression()

In [31]:
y_predt = lr.predict(x_test)

In [32]:
y_predt

array([-82.38160518,  35.99506399, -40.54430549,  27.49434119,
       -30.95507579, -66.1297635 , 103.36127426,   7.94353072,
        63.92457298,  62.56511912, -34.96464517,  31.92173377,
       -13.06456554,  15.85651443,  54.05223258,  31.86209495,
        -9.61671333,  74.41947999, -84.85372413, -49.57973975])

In [33]:
y_test

array([ -50.68393061,  -24.8716259 ,    1.78518195,   78.36090957,
        -80.31956567,  -65.87687533,  150.03859813,  -56.98045614,
         26.42853823,  173.95051775,  -75.80293811,   90.77729109,
         18.14403946,   22.79312888,   71.35713261,  -75.03482614,
        -55.01492421,   73.06170733,  -56.43338296, -137.96777929])

In [35]:
print("MAE",mean_absolute_error(y_test,y_predt))
print("MSE",mean_squared_error(y_test,y_predt))
print("R2 score",r2_score(y_test,y_predt))

MAE 46.07328987728782
MSE 3014.770653369395
R2 score 0.5464504190260016


In [40]:
lr.coef_

array([14.23672951, 76.83334943])

In [41]:
lr.intercept_


np.float64(8.125775480231454)